# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0156eeff9f084935dfcf2d7b4cac14ce3d782a16bafe659e77592d4c28d26006b514bbeb8b886c8dd592da3d1bfb41ad9dd9c3d660b77d0cd4d19e1e70e86208

test:
  secret_key_base: 9209f89ea6b5e6642f20bf1992c921cc41b8befb50c1a72f663a71adca8d5c8080178a2ffa0e474b2ecb7ea1818bbbfff1281c986d9969d59fc071fadf400732

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
